on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Install mingw tools
        run: sudo apt-get install -y mingw-w64 && echo "1"| sudo update-alternatives --config x86_64-w64-mingw32-gcc
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Build the project
        run: source ./.github/build
        shell: bash 
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'src/*.zip'